import 'package:flutter/foundation.dart';
import 'package:google_generative_ai/google_generative_ai.dart';
import 'dart:async';

/// Service to interact with Google's Gemini LLM
class LLMService {
  late final GenerativeModel _model;
  late final ChatSession _chat;
  bool _isInitialized = false;

  bool get isInitialized => _isInitialized;

  /// Initialize the LLM service with your API key
  /// Get your free API key from: https://makersuite.google.com/app/apikey
  Future<void> initialize(String apiKey) async {
    try {
      debugPrint('LLMService: Initializing Gemini...');

      _model = GenerativeModel(
        model: 'gemini-2.0-flash',
        apiKey: apiKey,
        generationConfig: GenerationConfig(
          temperature: 0.7,
          topK: 40,
          topP: 0.95,
          maxOutputTokens: 1024,
        ),
        safetySettings: [
          SafetySetting(HarmCategory.harassment, HarmBlockThreshold.medium),
          SafetySetting(HarmCategory.hateSpeech, HarmBlockThreshold.medium),
          SafetySetting(
              HarmCategory.sexuallyExplicit, HarmBlockThreshold.medium),
          SafetySetting(
              HarmCategory.dangerousContent, HarmBlockThreshold.medium),
        ],
      );

      // Start a chat session for conversation context
      _chat = _model.startChat(history: [
        Content.text(
          'You are Mira, a helpful and friendly voice assistant. '
          'Keep your responses concise and conversational (2-3 sentences max). '
          'Be helpful, informative, and engaging.',
        ),
        Content.model([
          TextPart(
              'Understood! I\'m Mira, your friendly voice assistant. I\'ll keep my responses brief and helpful. How can I assist you today?')
        ]),
      ]);

      _isInitialized = true;
      debugPrint('LLMService: Gemini initialized successfully');
    } catch (e) {
      debugPrint('LLMService: Failed to initialize: $e');
      rethrow;
    }
  }

  /// Send a message to the LLM and get a response
  Future<String> sendMessage(String userMessage) async {
    if (!_isInitialized) {
      throw Exception('LLM service not initialized. Call initialize() first.');
    }

    try {
      debugPrint('LLMService: Sending message: "$userMessage"');

      final response = await _chat.sendMessage(Content.text(userMessage));
      final text = response.text;

      if (text == null || text.isEmpty) {
        throw Exception('Empty response from LLM');
      }

      debugPrint('LLMService: Received response: "$text"');
      return text;
    } catch (e) {
      debugPrint('LLMService: Error sending message: $e');

      // Provide helpful error messages
      if (e.toString().contains('API key')) {
        throw Exception('Invalid API key. Please check your Gemini API key.');
      } else if (e.toString().contains('quota')) {
        throw Exception('API quota exceeded. Please try again later.');
      } else {
        throw Exception('Failed to get response: $e');
      }
    }
  }

  /// Stream a response as it is generated by the model.
  /// Emits text chunks as they arrive and completes with the full text.
  Stream<String> streamMessage(String userMessage) async* {
    if (!_isInitialized) {
      throw Exception('LLM service not initialized. Call initialize() first.');
    }

    try {
      debugPrint('LLMService: Streaming message: "$userMessage"');
      final stream = _chat.sendMessageStream(Content.text(userMessage));
      await for (final event in stream) {
        final text = event.text;
        if (text != null && text.isNotEmpty) {
          yield text;
        }
      }
    } catch (e) {
      debugPrint('LLMService: Streaming error: $e');
      rethrow;
    }
  }

  /// Reset the chat history (start a new conversation)
  void resetChat() {
    if (_isInitialized) {
      _chat = _model.startChat(history: [
        Content.text(
          'You are Mira, a helpful and friendly voice assistant. '
          'Keep your responses concise and conversational (2-3 sentences max). '
          'Be helpful, informative, and engaging.',
        ),
        Content.model([
          TextPart(
              'Understood! I\'m Mira, your friendly voice assistant. I\'ll keep my responses brief and helpful. How can I assist you today?')
        ]),
      ]);
      debugPrint('LLMService: Chat history reset');
    }
  }

  /// Dispose resources
  void dispose() {
    debugPrint('LLMService: Disposing...');
    _isInitialized = false;
  }
}
